modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="gtcables"
version="1.0.0 RC 1"
displayName="GregTech Cables"
authors="Sward"
description='''Suspended power cables for GregTech: Modern.'''
[[dependencies.gtcables]]
modId="forge"
mandatory=true
versionRange="[47.4.20,48)"
ordering="NONE"
side="BOTH"
[[dependencies.gtcables]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.gtcables]]
modId="gtceu"
mandatory=true
versionRange="[7.5.3,8)"
ordering="AFTER"
side="BOTH"
