modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="gtwires"
version="0.5.1"
displayName="GregTech Wires"
authors="Sward"
description='''Suspended GregTech EU cables, centimetre spools, and persistent event-driven networks.'''
[[dependencies.gtwires]]
modId="forge"
mandatory=true
versionRange="[47.4.20,48)"
ordering="NONE"
side="BOTH"
[[dependencies.gtwires]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
[[dependencies.gtwires]]
modId="gtceu"
mandatory=true
versionRange="[7.5.3,8)"
ordering="AFTER"
side="BOTH"
